"use strict";
// type discountType = "variable" | "fixed" | "none";
Object.defineProperty(exports, "__esModule", { value: true });
var Product_1 = require("./Product");
var ShoppingBasket_1 = require("./ShoppingBasket");
var VarDiscount_1 = require("./VarDiscount");
var FixDiscount_1 = require("./FixDiscount");
var NoDiscount_1 = require("./NoDiscount");
var cart = new ShoppingBasket_1.ShoppingBasket();
cart.addProduct(new Product_1.Product('Chair', 25, new FixDiscount_1.FixDiscount(15)));
//cart.addProduct(new Product('Chair', 25, new Discount("fixed", -10)));
cart.addProduct(new Product_1.Product('Table', 70, new VarDiscount_1.VarDiscount(45)));
cart.addProduct(new Product_1.Product('Bed', 100, new NoDiscount_1.NoDiscount()));
var tableElement = document.querySelector('#cart tbody');
cart.products.forEach(function (product) {
    var tr = document.createElement('tr');
    var td = document.createElement('td');
    td.innerText = product.name;
    tr.appendChild(td);
    td = document.createElement('td');
    td.innerText = product.originalPrice.toFixed(2) + " €";
    tr.appendChild(td);
    td = document.createElement('td');
    td.innerText = product.calculatePrice().toFixed(2) + " €";
    tr.appendChild(td);
    td = document.createElement('td');
    td.innerText = product.showCalculation();
    tr.appendChild(td);
    tableElement.appendChild(tr);
});
